build-GetScoresFunction:
	npm install
	npm test
	cp get-scores.js "$(ARTIFACTS_DIR)"
	cp -r node_modules "$(ARTIFACTS_DIR)"

build-AddScoreFunction:
	npm install
	npm test
	cp add-score.js "$(ARTIFACTS_DIR)"
	cp -r node_modules "$(ARTIFACTS_DIR)"
